services:
  nginx:
    image: nginx:1.0
    build: ./requirements/nginx/.
    depends_on:
      - wordpress
    restart: always
    ports:
      - "443:443"
    volumes:
      - wp_data:/var/www/html
    environment:
      DOMAIN_NAME: ${DOMAIN_NAME}
    networks:
      - JonaNet

  wordpress:
    image: wordpress:1.0
    build: ./requirements/wordpress/.
    depends_on:
      - mariadb
    restart: always
    environment:
      WORDPRESS_DB_NAME: ${MYSQL_DATABASE}
      WORDPRESS_DB_USER: ${MYSQL_USER}
      WORDPRESS_DB_HOST: ${MYSQL_HOST}
      DOMAIN_NAME: ${DOMAIN_NAME}
    volumes:
      - wp_data:/var/www/html
      - ../secrets/db_password.txt:/run/secrets/db_password:ro
      - ../secrets/credentials.txt:/run/secrets/credentials:ro
    secrets:
      - db_password
      - credentials
    networks:
      - JonaNet

  mariadb:
    image: mariadb:1.0
    build: ./requirements/mariadb/.
    restart: always
    environment:
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_ROOT_PASSWORD_FILE: /run/secrets/db_root_password
    volumes:
      - mariadb_data:/var/lib/mysql
      - ../secrets/db_password.txt:/run/secrets/db_password:ro
      - ../secrets/db_root_password.txt:/run/secrets/db_root_password:ro
    secrets:
      - db_password
      - db_root_password
    networks:
      - JonaNet

networks:
  JonaNet:

volumes:
  wp_data:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /home/joklein/data/wp_data
  mariadb_data:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /home/joklein/data/mariadb_data

secrets:
  db_password:
    file: ../secrets/db_password.txt
  db_root_password:
    file: ../secrets/db_root_password.txt
  credentials:
    file: ../secrets/credentials.txt

# Nginx: receives request, serves files or forwards PHP to WordPress
# WordPress: runs PHP, talks to MariaDB, builds page
# MariaDB: MariaDB is the database backend for WordPress, answers WordPress queries
# Flow: Browser -> Nginx -> WordPress -> MariaDB -> WordPress -> Nginx -> Browser
